name: Go

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Download dependencies
        run: go mod download

      - name: Build CLI
        run: go build -v -o commitlint ./cmd/cli

      - name: Build Webhook Server
        run: go build -v -o commitlint-webhook-server ./cmd/webhook-server

      - name: Test
        run: go test -v ./...

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: commitlint-cli-linux-amd64
          path: |
            commitlint
            .commitlintrc.yml
            README.md
            LICENSE.md

      - name: Upload Webhook Server artifact
        uses: actions/upload-artifact@v4
        with:
          name: commitlint-webhook-server-linux-amd64
          path: |
            commitlint-webhook-server
            webhook-server.yml.example
            docker-compose.yml.example
            .env.example
            README.md
            LICENSE.md
